version: '3'
services:
  mongo:
    image: mongo
    volumes:
      - "dbdata:/data/db"
    ports:
      - "27017:27017"
  app:
    restart: always
    volumes:
      - ".:/usr/src/app"
    build: .
    command: yarn run devstart
    ports:
      - "3000:3000"
    depends_on:
      - mongo
volumes:
  dbdata:
